name: 'Get Karma Dependencies'
description: 'sets the node version & fetches dependencies for karma tests'
runs:
  using: composite
  steps:
    # this overrides previous versions of the node runtime that was set.
    # jobs that need a different version of the Node runtime should explicitly
    # set their node version after running this step
    - name: Use Node Version from Volta
      uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
      with:
        node-version-file: './package.json'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci
      shell: bash
      working-directory: test/karma
